vercel env add MONGO_URI production
# الصق مثلاً: mongodb+srv://<DB_USER>:<DB_PASSWORD>@<CLUSTER_HOST>/car-auction

vercel env add SESSION_SECRET production
vercel env add JWT_SECRET production
vercel env add ADMIN_NAME production        # إن كنت بحاجة له
vercel env add ADMIN_PHONE production